BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "OrderDetail" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"ProductID"	TEXT,
	"ProductName"	TEXT,
	"Quantity"	TEXT,
	"Price"	TEXT,
	"Discount"	TEXT
);
COMMIT;
